# Generated by Django 4.2.4 on 2023-08-24 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('description', models.CharField(max_length=144)),
                ('is_high_priority', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('job_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Des', 'At Design'), ('Prod', 'In Production'), ('Hold', 'On Hold'), ('Assy', 'At Assembly'), ('Awt', 'Awaiting Delivery'), ('Del', 'Delivered'), ('Can', 'Cancelled')], default='Des', max_length=4)),
                ('purchase_order_number', models.CharField(max_length=24)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.customer')),
                ('project_captains', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
