# Generated by Django 4.2.4 on 2023-09-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['job_code']},
        ),
    ]
