# Generated by Django 4.2.4 on 2023-08-24 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AncillaryJobCode',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=42)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TaskTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('Adm', 'Admin'), ('Des', 'Design'), ('Doc', 'Documentation'), ('Dwg', 'Drawings'), ('Gen', 'General')], default='Gen', max_length=3)),
                ('elapsed_time', models.DurationField(blank=True, null=True)),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_stopped', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('is_running', models.BooleanField(default=False)),
                ('is_ongoing', models.BooleanField(default=True)),
                ('ancillary_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timesheets.ancillaryjobcode')),
                ('job_code', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
