# Generated by Django 4.2.4 on 2023-09-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_alter_tasktime_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ancillaryjobcode',
            options={'ordering': ['description']},
        ),
        migrations.AlterModelOptions(
            name='tasktime',
            options={'ordering': ['date_created']},
        ),
    ]
