# Generated by Django 4.2.4 on 2023-08-24 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=48, null=True)),
                ('lastName', models.CharField(blank=True, max_length=48, null=True)),
                ('role', models.CharField(choices=[('Des', 'Designer'), ('Man', 'Manager'), ('Fit', 'Fitter'), ('Mac', 'Machinist'), ('Adm', 'Admin'), ('Gen', 'General'), ('Ele', 'Electrician'), ('Wel', 'Welder')], default='Gen', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
