# Generated by Django 4.2.4 on 2024-03-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting_floor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fittingtask',
            name='time_started',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fittingtask',
            name='time_stopped',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
