# Generated by Django 4.2.4 on 2024-03-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting_floor', '0002_alter_fittingtask_time_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fittingtask',
            name='notes',
            field=models.TextField(blank=True, max_length=240, null=True),
        ),
    ]
